title: "Welcome to my site"
date: 2018-05-31
author: Sahil-Singh
email: 2016ucs0025@gmail.com
description: > 
 This is my first site to created by github directely. Now I'm learn how to create site throw github.
 Thanks to visit my site.

# social links
github_username:  https://github.com/sahilsingh21

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
